import { BookInterface } from "./app/book-interface";

export const BOOKS :Array<BookInterface>= [
    {id:1, title:"Père Riche,Père Pauvre", author:"Robert",status:"En cours"},
    {id:2, title:"Zero burg", author:"Kate",status:"En attente"},
    {id:3, title:"Père Riche,Père Pauvre", author:"Robert",status:"Terminer"},
    {id:4, title:"Père Riche,Père Pauvre", author:"Robert",status:"Archiver"},
    {id:5, title:"Père Riche,Père Pauvre", author:"Robert",status:"En cours"},
    {id:6, title:"Zero burg", author:"Kate",status:"En attente"},
    {id:7, title:"Père Riche,Père Pauvre", author:"Robert",status:"Terminer"},
    {id:8, title:"Père Riche,Père Pauvre", author:"Robert",status:"Archiver"},
    {id:9, title:"Père Riche,Père Pauvre", author:"Robert",status:"En cours"},
    {id:10, title:"Zero burg", author:"Kate",status:"En attente"},
    {id:11, title:"Père Riche,Père Pauvre", author:"Robert",status:"Terminer"},
    {id:12, title:"Père Riche,Père Pauvre", author:"Robert",status:"Archiver"},
    {id:13, title:"Père Riche,Père Pauvre", author:"Robert",status:"En cours"},
    {id:14, title:"Zero burg", author:"Kate",status:"En attente"},
    {id:15, title:"Père Riche,Père Pauvre", author:"Robert",status:"Terminer"},
    {id:16, title:"Père Riche,Père Pauvre", author:"Robert",status:"Archiver"},
    {id:17, title:"Père Riche,Père Pauvre", author:"Robert",status:"En cours"},
    {id:18, title:"Zero burg", author:"Kate",status:"En attente"},
    {id:19, title:"Père Riche,Père Pauvre", author:"Robert",status:"Terminer"},
    {id:20, title:"Père Riche,Père Pauvre", author:"Robert",status:"Archiver"},
    {id:21, title:"Père Riche,Père Pauvre", author:"Robert",status:"En cours"},
    {id:22, title:"Zero burg", author:"Kate",status:"En attente"},
    {id:23, title:"Père Riche,Père Pauvre", author:"Robert",status:"Terminer"},
    {id:24, title:"Père Riche,Père Pauvre", author:"Robert",status:"Archiver"},
    {id:25, title:"Père Riche,Père Pauvre", author:"Robert",status:"En cours"},
    {id:26, title:"Zero burg", author:"Kate",status:"En attente"},
    {id:27, title:"Père Riche,Père Pauvre", author:"Robert",status:"Terminer"},
    {id:28, title:"Père Riche,Père Pauvre", author:"Robert",status:"Archiver"},
    {id:29, title:"Père Riche,Père Pauvre", author:"Robert",status:"En cours"},
    {id:30, title:"Zero burg", author:"Kate",status:"En attente"},
    {id:31, title:"Père Riche,Père Pauvre", author:"Robert",status:"Terminer"},
    {id:32, title:"Père Riche,Père Pauvre", author:"Robert",status:"Archiver"},
    ]